M48
; DRILL file {KiCad (6.0.8-1)-1} date Wednesday, January 25, 2023 at 05:11:08 PM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-01-25T17:11:08-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.8-1)-1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1181
%
G90
G05
T1
X3.3641Y-3.4495
X3.3641Y-4.2369
X3.7874Y-3.4488
X3.7874Y-4.2362
T0
M30
